# ==========================================
# Configuration de l'application MP3 Web
# ==========================================

# Serveur
server.port=8080

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/mp3_db
spring.datasource.username=postgres
spring.datasource.password=Fifaliana!
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Thymeleaf
spring.thymeleaf.cache=false

# Taille max upload fichier
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# Repertoire de stockage des MP3 uploades
mp3.storage.path=./uploads
